### ISSUE TITLE
Tool locking up when file uglified

### ISSUE THREAD

**Issue by DaveO-Home** [canjs/devtools#16]
Locking up, had to rebuild without uglify to fix. Is there a way to terminate the tool?

**Comment by justinbmeyer** [comment]
@DaveO-Home is your page public?  It would be helpful to know why it's locking up.

**Comment by phillipskevin** [comment]
If you're running into problems, you can disable it in chrome://extensions/.

Also, if you're on a page using devtools, you can "Inspect Element" in the devtools panel in order to debug the devtools:

![inspect-devtools](https://user-images.githubusercontent.com/5851984/39583999-f36a0cb0-4eb6-11e8-9dea-d13dec74a46d.gif)

You can see any errors here (I'm running an unreleased version which obviously has some errors). Once in this window you can also CMD+R to reload the devtools (or CTRL+R on windows).

**Comment by DaveO-Home** [comment]
The page is not public, but any large single line js file should reproduce.  When it locked up, I terminated the tab and then restarted the tab and brought up devtools. It kept going to the source tab and I couldn't get to console or inspect.  I'll try the CMD+R.

**Comment by DaveO-Home** [comment]
Well, it looks like a Chrome issue; I disabled canjs/devtool with same results. I even have source-maps.
I'm on Fedora 27 with Chrome 66.0.3359.117 (Official Build) (64-bit)

**Comment by DaveO-Home** [comment]
Ok, it looks like I have fat fingered this. The canjs/dev icon is greyed out but I'm definitely on a canjs page.  So how to activate?

**Comment by phillipskevin** [comment]
You should just have to open devtools and the panels will show up if your page has a `window.can` available. I'm working on making this work more consistently. Should have a new release out in the next week.

**Comment by DaveO-Home** [comment]
Not sure how to "open devtools"; I have the vue-tool also installed and when it detects a vue page a tab appears in the chrome dev/tools.  When I click on the canjs icon  'CanJS DevTools' sends me to the store to install it. I can wait for the new release.

**Comment by phillipskevin** [comment]
I just meant when you open the chrome devtools.

Right now there is no dedicated tab for CanJS Devtools. We're considering adding one. Please let us know what would be useful to have in a tab like this if you have ideas.

What CanJS devtools adds are "sidebars" to the chrome devtools Elements and Sources tabs.

When you are on the Elements tab, two new sidebars will show up on the right (CanJS ViewModel and CanJS Bindings Graph). When you are on the Sources tab, a sidebar will be displayed for CanJS Queues Stack.

**Comment by phillipskevin** [comment]
The canjs global build will add `window.can` if you're using individual modules, you can import `can-debug`, which will also set up `window.can`.

**Comment by justinbmeyer** [comment]
I show how it works here: https://youtu.be/zsQ0p0xv5oI?t=643

**Comment by DaveO-Home** [comment]
Yes, I got the ViewModel to show, added can-debug. thanks
