### ISSUE TITLE
Switching between instances of the same component alters the properties of the second component

### ISSUE THREAD

**Issue by roemhildtg** [canjs/devtools#25]
1. Click on one component and inspect it. 
2. Alter some of the attributes in the VM editor
3. Click Save
4. Click on another component with the inspector. 
5. Observe problems. Sometimes this will simply copy properties from one component to another. Other times it seems to completely remove the other components properties.

**Comment by phillipskevin** [comment]
This is fixed now because the ViewModel Editor no longer auto-saves, but there is a related issue here: https://github.com/canjs/can-devtools-components/issues/32.
