### ISSUE TITLE
Serializing ViewModel data can be very slow

### ISSUE THREAD

**Issue by phillipskevin** [canjs/devtools#41]
Sometimes it can take a long time to serialize data on a ViewModel:

https://github.com/canjs/devtools/blob/264970dc0f6d5d613ce0488914ee91e74aa12151/canjs-devtools-injected-script.js#L191

For example, the `components` property on the [Multiple Modals Recipe](https://codepen.io/justinbmeyer/pen/mjyjQN?editors=0010) takes roughly 500ms.

Since this function gets called every 100ms, this can lock up the browser.

**Comment by phillipskevin** [comment]
We should definitely only call the function again _after_ the previous call returns:

https://github.com/canjs/devtools/blob/264970dc0f6d5d613ce0488914ee91e74aa12151/viewmodel-editor/viewmodel-editor.mjs#L71

**Comment by justinbmeyer** [comment]
We should make sure types like Component have no enumerable props, that way that would serialize to nothing. Or in components case, we can add a symbol.

**Comment by phillipskevin** [comment]
I opened an issue for this, but I'll also need to handle this on the devtools side so that if for whatever reason serialization is slow it doesn't blow up devtools.

**Comment by phillipskevin** [comment]
The latest release no longer tried to serializes DOM nodes.
