### ISSUE TITLE
Devtools Panel UX Issues

### ISSUE THREAD

**Issue by phillipskevin** [canjs/devtools#49]
Now that the CanJS Panel has been released, this issue will consolidate any outstanding UX issues. If you find something, please leave a comment and I'll add it to the description.

## P0s

- [x] `expandedKeys` is not being passed correctly from the ViewModel Editor in the Elements Panels sidebar, so data is never retrieved for expanded keys

- [x] `getNodeById` doesn't work if there are sibling components "after" selected node

## P1s

- [x] ~~should show an indicator when loading data for an expanded property~~ should refresh data faster when expanding a property

- [x] should show a message when a property does not have serializable properties (elements for example)

- [x] should show an error when serializing a property throws an exception

- [x] should handle nulls... right now they're treated as HTML Elements

- [x] should show an info message for empty object / arrays / map / lists

- [x] ViewModel Editor and Component Tree should scroll independently (instead of the entire page scrolling):

![viewmodel-editor-overflow](https://user-images.githubusercontent.com/5851984/50649133-b165ae80-0f42-11e9-8eef-fda499f2926f.gif)

- [x] ViewModel Editor Header needs some space:

![image](https://user-images.githubusercontent.com/78602/50650801-220eca00-0f47-11e9-8589-99da216c0d9d.png)

**Comment by justinbmeyer** [comment]
![image](https://user-images.githubusercontent.com/78602/50650801-220eca00-0f47-11e9-8589-99da216c0d9d.png)
