### ISSUE TITLE
DevTools gets out of sync with the page after two refreshes

### ISSUE THREAD

**Issue by chasenlehara** [canjs/devtools#69]
Steps to reproduce:

1. Load a page & open DevTools
2. Click refresh
3. Wait for DevTools to refresh the tree
4. Click refresh again

Expected result: DevTools refreshes the component tree

Actual result: DevTools is broken / out of sync with the page

![refreshing bug 2](https://user-images.githubusercontent.com/10070176/52082842-b8d4a380-2552-11e9-87f6-ff873255a6ba.gif)

**Comment by phillipskevin** [comment]
@chasenlehara I put out a fix that I think addresses this. Can you give this another try with version 0.0.36 (you can check the version in chrome://extensions)?

Also, can you double check https://github.com/canjs/devtools/issues/68?

**Comment by chasenlehara** [comment]
Both this issue and https://github.com/canjs/devtools/issues/68 appear to be fixed 0.0.36 🎉

**Comment by phillipskevin** [comment]
Thanks for checking @chasenlehara!
