### ISSUE TITLE
Remove "ViewModel" wording

### ISSUE THREAD

**Issue by phillipskevin** [canjs/devtools#78]
With CanJS 6, we no longer have a separate ViewModel. We should change things that say "viewModel" or "ViewModel" to a term that makes sense for both `can-component` and `can-stache-element`. Perhaps "Observable Properties".

**Comment by cherifGsoul** [comment]
I suggest to use `props`!

**Comment by phillipskevin** [comment]
Some examples:

![image](https://user-images.githubusercontent.com/5851984/68318520-8d06c100-0082-11ea-9c2a-0841395fba26.png)

![image](https://user-images.githubusercontent.com/5851984/68318598-a576db80-0082-11ea-8b5c-bbb118f5303c.png)

![image](https://user-images.githubusercontent.com/5851984/68318626-af004380-0082-11ea-83d6-d2c3d1d17cbe.png)

**Comment by phillipskevin** [comment]
We'll also need to update https://canjs.com/doc/guides/debugging.html once devtools is changed, but we can open a separate issue

**Comment by cherifGsoul** [comment]
I reopened the issue b/c the debugging guide is not updated yet.
