### ISSUE TITLE
CanJS 6 version errors 

### ISSUE THREAD

**Issue by cherifGsoul** [canjs/devtools#85]
The changes for CanJS 6 is not working like in the following screenshot:

<img width="1420" alt="__panel_and_DevTools_-_devtools___devtools_bundled_devtools_app_html_remoteBase_https___chrome-devtools-frontend_appspot_com_serve_file__021b9028c246d820be17a10e5b393ee90f41375e__can_dock_true_panel_elements_dockSide_undocked" src="https://user-images.githubusercontent.com/109013/68505728-3e1a8080-0268-11ea-94fe-4f8c3cecbd48.png">

Even with a component node selected in the left panel, nothing is displayed in the `Observable Properties Editor` and the console has errors.

The error is in this line:
https://github.com/canjs/devtools/blob/4bcf0d6f610bb3c9d6ed409de7f793785c606e3c/panel/panel.mjs#L303

Maybe we should update `panel` component properties, `viewModelData` properties to have default value as `new ObservableObject` and `breakpoints` to have `new ObservableArray` as default value.

- [ ] Use canReflect
- [ ] Fix Expandable Panel content, use template customization  instead of `<content/>`
- [ ] Fix Type errors, most of errors can be fixed by setting a default value

**Comment by justinbmeyer** [comment]
Why are we assuming updateDeep instead of using canReflect?
